### ISSUE TITLE
Bug report: Refi page - broken pdf link

### ISSUE THREAD

**Issue by TylerAPfledderer** [ethereum/ethereum-org-fork#102]
### Describe the bug

The link `A detailed report by the Taskforce for Scaling Voluntary Carbon Markets` in the `Additional reading on ReFi` section contains a link that was parsed incorrectly.

Has the href value of `https://ethereum-org-fork.netlify.app/content/refi/https:/www.iif.com/Portals/1/Files/TSVCM_Report.pdf`

### To reproduce

1. Go to https://ethereum-org-fork.netlify.app/refi#additional-reading-on-refi
2. Select `A detailed report by the Taskforce for Scaling Voluntary Carbon Markets`
3. New tab ends at a 404

### Expected behavior

Supposed to have an href value of `https://www.iif.com/Portals/1/Files/TSVCM_Report.pdf` [that was provided in refi.md](https://github.com/ethereum/ethereum-org-fork/blob/d32b2fbce742b7a66e9641a1774aa181d90e1984/public/content/refi/index.md?plain=1#L78).

### Additional context

The update to `BaseLink` in the migration to NextJS has added a condition check with `isPdf` where the `href` sent to the component is converted to a relative path. Unfortunately, this PDF appears to be intended to originate from an external source.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by nhsz** [comment]
@TylerAPfledderer thanks for reporting this 🙌 I've opened this PR that should fix it https://github.com/ethereum/ethereum-org-fork/pull/109
