### ISSUE TITLE
Main nav dropdowns not closing

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-fork#37]
### Describe the bug

The navbar dropdowns are not closing when you click and open another dropdown.

![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/a8023655-36ee-479c-8fa5-e967708dfebc)

### To reproduce

1. Go to https://ethereum-org-fork.netlify.app/bridges
2. Click on the dropdowns
3. See error

### Expected behavior

Clicking in other dropdowns should be the same as when you click outside of the dropdown, it should close it.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
Should consider bringing in https://github.com/ethereum/ethereum-org-website/pull/10075 if and when possible to see if it will automatically solve this issue.

**Comment by pettinarip** [comment]
Thanks @TylerAPfledderer. Ok, I'll try to look into that PR again and see if we can bring it in.
