### ISSUE TITLE
Lint failing

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-fork#62]
### Describe the bug

Our current lint process is failing because we don't have `esling-config-prettier` installed.
![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/97130e94-89ea-431d-89ce-5d00b1cf6ead)

### To reproduce

Run `yarn lint`.

### Expected behavior

We need to install `esling-config-prettier` + fix all the current error & warnings.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
@pettinarip if you'd like, I can take this as well!

**Comment by TylerAPfledderer** [comment]
@pettinarip in fixing errors and warnings: how would you prefer handling escaped characters?

```tsx
<p>
  When&apos;s it shipping?
</p>
```
or
```tsx
<p>
  {`When's it shipping?`}
</p>
```

Probably want this situation clarified in the docs as well.

**Comment by pettinarip** [comment]
> @pettinarip in fixing errors and warnings: how would you prefer handling escaped characters?
> 
> ```tsx
> <p>
>   When&apos;s it shipping?
> </p>
> ```
> 
> or
> 
> ```tsx
> <p>
>   {`When's it shipping?`}
> </p>
> ```
> 
> Probably want this situation clarified in the docs as well.

@nhsz @wackerow @corwintines ^ what do you guys think?

In other EF projects, we have been using the `&apos;` way. So, probably it is better to keep them consistent.

=====

However, I must say that I find this rule annoying but understand the benefits haha it is what it is 🤷🏼

**Comment by nhsz** [comment]
> &apos;

In favor of keeping `&apos;`

**Comment by nhsz** [comment]
> > @pettinarip in fixing errors and warnings: how would you prefer handling escaped characters?
> > ```tsx
> > <p>
> >   When&apos;s it shipping?
> > </p>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```tsx
> > <p>
> >   {`When's it shipping?`}
> > </p>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Probably want this situation clarified in the docs as well.
> 
> @nhsz @wackerow @corwintines ^ what do you guys think?
> 
> In other EF projects, we have been using the `&apos;` way. So, probably it is better to keep them consistent.
> 
> =====
> 
> However, I must say that I find this rule annoying but understand the benefits haha it is what it is 🤷🏼

In favor of keeping `&apos;`

**Comment by corwintines** [comment]
I prefer

```
{`When's it shipping?`}
```

But, for consistency sake, I agree and can keep `&apos;`
