### ISSUE TITLE
Anchor links in rtl

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-fork#78]
### Describe the bug

Anchor icon showing on the left in rtl languages.

![image](https://github.com/ethereum/ethereum-org-fork/assets/468158/7c7c2422-825f-4885-9681-7dc058fde4bf)

### To reproduce

https://ethereum-org-fork.netlify.app/fa/refi

### Expected behavior

I'd expect the icon to be on the right side on `rtl` languages.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by TylerAPfledderer** [comment]
@pettinarip So I see this is related to the `IdAnchor` component, where there positioning prop used is `InsetInlineEnd`. However, in this prop's transformation under the hood it is looking for a `direction` value in the Chakra extended theme. And then it renders either the `left` or `right` prop in production.

A short-term workaround here is to access this prop within `sx` and specifically doing this:
```ts
sx={{ 'inset-inline-end': '100%' }} // With kebab-case
```
 because it will just be recognized as a static prop. Long-term solution is to look at one of the strategies from the [RTL support docs](https://chakra-ui.com/docs/styled-system/rtl-support)

**Comment by pettinarip** [comment]
> @pettinarip So I see this is related to the `IdAnchor` component, where there positioning prop used is `InsetInlineEnd`. However, in this prop's transformation under the hood it is looking for a `direction` value in the Chakra extended theme. And then it renders either the `left` or `right` prop in production.
> 
> A short-term workaround here is to access this prop within `sx` and specifically doing this:
> 
> ```ts
> sx={{ 'inset-inline-end': '100%' }} // With kebab-case
> ```
> 
> because it will just be recognized as a static prop. Long-term solution is to look at one of the strategies from the [RTL support docs](https://chakra-ui.com/docs/styled-system/rtl-support)

Interesting, thanks for the context.

I'd lean toward implementing the long-term RTL solution rather than the patch since IMO this is something we need to address anyway throughout the codebase.

What do you think @wackerow @nhsz @corwintines?

**Comment by wackerow** [comment]
Would definitely prefer to properly implement the `dir` attribute. This has never _fully_ been implemented for RTL languages on the existing Gatsby site

**Comment by TylerAPfledderer** [comment]
> Would definitely prefer to properly implement the `dir` attribute. This has never _fully_ been implemented for RTL languages on the existing Gatsby site

Indeed, because Gatsby makes that process just a tiny bit complicated! lol

**Comment by nhsz** [comment]
> @pettinarip So I see this is related to the `IdAnchor` component, where there positioning prop used is `InsetInlineEnd`. However, in this prop's transformation under the hood it is looking for a `direction` value in the Chakra extended theme. And then it renders either the `left` or `right` prop in production.
> 
> A short-term workaround here is to access this prop within `sx` and specifically doing this:
> ```ts
> sx={{ 'inset-inline-end': '100%' }} // With kebab-case
> ```
>  because it will just be recognized as a static prop. Long-term solution is to look at one of the strategies from the [RTL support docs](https://chakra-ui.com/docs/styled-system/rtl-support)

@TylerAPfledderer @pettinarip Noting that these docs are a bit outdated and refer to previous versions of Next, eg: `getInitialProps` usage is discouraged since a while (was replaced by `getStaticProps/getServerSideProps`), so it'd need some research to come with a more up to date solution

**Comment by TylerAPfledderer** [comment]
Indeed! 😅  

In doing some research, `getInitialProps` seems to behave a little differently when in `_document.tsx` though are essentially the same.

- `getInitialProps` in the Document context does not run on client-side transitions
- `getInitialProps` for exported pages run on the server at initial load, and then run on the client-side when transitioning between pages.

Overall, `_document` does not currently support the use of `getStaticProps` or `getServerSideProps`. I have tried using the example from the docs and completely removed the `getInitialProps` and it was still working fine. Not sure if that breaks anything though after build. Can't check without running a preview deploy of the changes.

`this` context has to be called in a class of course to access the next data provided in an injected script. 
`<script id="__NEXT_DATA__" type="application/json">`

I think this is independent of using `getInitialProps`.
