### ISSUE TITLE
Update docs: new TS conventions

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-fork#86]
Update the [current convention doc](https://github.com/ethereum/ethereum-org-fork/blob/dev/docs/next-docs/code-conventions.md) with the new accepted TS conventions discussed in https://github.com/ethereum/ethereum-org-website/issues/11421

This should cover points 1, 2, and 4 from the proposal.

**Comment by pettinarip** [comment]
cc @TylerAPfledderer

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment. Thank you!
