### ISSUE TITLE
ESlint: add import sort plugin

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-fork#87]
Add the `eslint-plugin-simple-import-sort` plugin along with the suggested order proposed in https://github.com/ethereum/ethereum-org-website/issues/8865

**Note:** the scope of this issue does not include adding the prettier plugin. That should be covered in https://github.com/ethereum/ethereum-org-fork/issues/62

**Comment by pettinarip** [comment]
cc @TylerAPfledderer

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment. Thank you!
